sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull mysql/mysql-server:5.7
  - docker run -e MYSQL_ROOT_PASSWORD=root -d mysql/mysql-server:5.7 -p 3306:3306

before_script:
  - mysql -e 'create database `tic-tac-toe`;'
  - mysql -e 'SET PASSWORD FOR 'root'@'localhost' = PASSWORD("root");'

script:
  - mvn clean verify