sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
    - MYSQL_DATABASE: tic-tac-toe
    - MYSQL_USER: root
    - MYSQL_PASSWORD: root

before_install:
  - docker pull mysql/mysql-server:5.7
  - docker run -d -p localhost:3306/tic-tac-toe mysql/mysql-server:5.7

script:
  - mvn clean verify