spring:
  profiles:
    active: prod

  liquibase:
    contexts: prod
    drop-first: true

  datasource:
    hikari:
      maximum-pool-size: 6
      minimum-idle: 3
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tic-tac-toe
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    properties:
        jadira.usertype.autoRegisterUserTypes: true
        hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: it
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

  liquibase:
    contexts: it

---
spring:
  profiles: prod

  liquibase:
      contexts: prod
      drop-first: false

  datasource:
      hikari:
        maximum-pool-size: 6
        minimum-idle: 3
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgres://vzbggyazvthetw:27cc2686252272a5af95224a5ef36001844ed251adea345afbb9f2586a733a94@ec2-54-225-76-201.compute-1.amazonaws.com:5432/df6t57ug8o4rs8
      username: postgres
      password: postgres

  database-platform: org.hibernate.dialect.PostgreSQL9Dialect